name: "[Kafka API] Generate Documents"

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  kafka-api-build-doc:
    runs-on: ubuntu-22.04
    env:
        BUILD_SUB_DIR: build/sub-build

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Install Dependencies
        run: |
          mkdir -p $BUILD_SUB_DIR
          cd $BUILD_SUB_DIR

          # 1. Install python3-pip
          sudo apt install -y python3-pip
          pip3 install markdown
          # 2. Install doxygen
          sudo apt install -y doxygen

      - name: Config
        run: |
          cd $BUILD_SUB_DIR
          cmake ../.. -DBUILD_OPTION_DOC_ONLY=ON

      - name: Build
        run: |
          cd $BUILD_SUB_DIR
          make VERBOSE=1

      - name: Collect
        run: |
          mkdir document
          cp $BUILD_SUB_DIR/doc/index.html document
          cp -r $BUILD_SUB_DIR/doc/markdown document
          cp -r $BUILD_SUB_DIR/doc/doxygen document

      - name: Upload Artifact
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        with:
            name: document
            path: document


  kafka-api-deploy-doc:
    needs: [kafka-api-build-doc]
    if: github.event_name == 'push'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          persist-credentials: false

      - name: Download Artifacts
        uses: actions/download-artifact@18f0f591fbc635562c815484d73b6e8e3980482e # v1.0.0
        with:
          name: document

      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@8817a56e5bfec6e2b08345c81f4d422db53a2cdc # v4.3.3
        with:
          branch: gh-pages
          folder: document

